FROM alpine:edge

ENV SHADOWSOCKS_VERSION master
ENV SIMPLE_OBFS_VERSION master
ENV KCPTUN_VERSION 20200409
ENV SHADOWSOCKS_URL https://github.com/shadowsocks/shadowsocks-libev.git
ENV SIMPLE_OBFS_URL https://github.com/shadowsocks/simple-obfs.git
ENV KCPTUN_URL https://github.com/xtaci/kcptun/releases/download/v$KCPTUN_VERSION/kcptun-linux-amd64-$KCPTUN_VERSION.tar.gz

RUN apk upgrade --update \
  && apk add --no-cache --virtual .build-deps build-base flex bison alpine-sdk linux-headers ca-certificates \
  udns-dev pcre-dev zlib-dev libcap autoconf automake c-ares-dev libtool git gawk flex bison libev-dev mbedtls-static mbedtls-dev libsodium-dev patch curl \
  && cd /tmp \
  && git clone --recursive --depth 1 $SHADOWSOCKS_URL \
  && cd shadowsocks-libev \
  && ./autogen.sh \
  && ./configure --prefix=/usr --disable-documentation --disable-ssp \
  && make install \
  && ls /usr/bin/ss-* | xargs -n1 setcap cap_net_bind_service+ep \
  && cd /tmp \
  && git clone --recursive --depth 1 $SIMPLE_OBFS_URL \
  && cd simple-obfs \
  && ./autogen.sh \
  && ./configure --disable-documentation --disable-ssp \
  && make install \
  && ls /usr/local/bin/obfs-* | xargs -n1 setcap cap_net_bind_service+ep \
  && cd /tmp \
  && curl -sSLO $KCPTUN_URL \
  && tar xfz kcptun-linux-amd64-${KCPTUN_VERSION}.tar.gz \
  && mv server_linux_amd64 /usr/bin/kcptun-server \
  && mv client_linux_amd64 /usr/bin/kcptun-client \
  && runDeps="$( \
      scanelf --needed --nobanner /usr/bin/ss-* /usr/local/bin/obfs-* \
        | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
        | xargs -r apk info --installed \
        | sort -u \
      )" \
  && apk add --virtual .run-deps $runDeps ca-certificates rng-tools libsodium tzdata \
  && apk add --virtual .sys-deps bash \
  && apk del .build-deps \
  && rm -rf /tmp/* /var/cache/apk/*

ADD sysctl.conf /etc/sysctl.conf
ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
